---
- hosts: devstack
  become: true

  tasks:
    - name: Do not accept ssh client locales
      lineinfile: dest=/etc/ssh/sshd_config regexp="^AcceptEnv LANG LC_*" line="# ^AcceptEnv LANG LC_*"

    - name: Install git
      apt: name=git update_cache=yes cache_valid_time=3600

    - name: Clone devstack
      git:
        repo: https://git.openstack.org/openstack-dev/devstack
        dest: /opt/devstack

    - name: Create stack user
      command: /opt/devstack/tools/create-stack-user.sh

    - name: Delete previous clone
      file: path=/opt/stack/devstack state=absent

    - name: Clone devstack
      command: su - stack -c 'git clone https://git.openstack.org/openstack-dev/devstack /opt/stack/devstack'

    - name: Set local.conf
      copy: src=files/local.conf dest=/opt/stack/devstack/local.conf owner=stack group=stack mode=0644

    - name: Launch the stack
      command: su - stack -c 'cd devstack && ./stack.sh'